#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sablon.Modal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hasta")]
	public partial class HastaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdbo_tblPatolojikVeriler(dbo_tblPatolojikVeriler instance);
    partial void Updatedbo_tblPatolojikVeriler(dbo_tblPatolojikVeriler instance);
    partial void Deletedbo_tblPatolojikVeriler(dbo_tblPatolojikVeriler instance);
    partial void InserttblTakipVerileri(tblTakipVerileri instance);
    partial void UpdatetblTakipVerileri(tblTakipVerileri instance);
    partial void DeletetblTakipVerileri(tblTakipVerileri instance);
    partial void InserttblDemografik_Ozellikleri(tblDemografik_Ozellikleri instance);
    partial void UpdatetblDemografik_Ozellikleri(tblDemografik_Ozellikleri instance);
    partial void DeletetblDemografik_Ozellikleri(tblDemografik_Ozellikleri instance);
    partial void InserttblDoktor(tblDoktor instance);
    partial void UpdatetblDoktor(tblDoktor instance);
    partial void DeletetblDoktor(tblDoktor instance);
    partial void InserttblHastaBilgileri(tblHastaBilgileri instance);
    partial void UpdatetblHastaBilgileri(tblHastaBilgileri instance);
    partial void DeletetblHastaBilgileri(tblHastaBilgileri instance);
    partial void InserttblOperatif_Ozellikler(tblOperatif_Ozellikler instance);
    partial void UpdatetblOperatif_Ozellikler(tblOperatif_Ozellikler instance);
    partial void DeletetblOperatif_Ozellikler(tblOperatif_Ozellikler instance);
    partial void InserttblPosOperatif_Ozellikler(tblPosOperatif_Ozellikler instance);
    partial void UpdatetblPosOperatif_Ozellikler(tblPosOperatif_Ozellikler instance);
    partial void DeletetblPosOperatif_Ozellikler(tblPosOperatif_Ozellikler instance);
    partial void InserttblOpTuru(tblOpTuru instance);
    partial void UpdatetblOpTuru(tblOpTuru instance);
    partial void DeletetblOpTuru(tblOpTuru instance);
    #endregion
		
		public HastaDBDataContext() : 
				base(global::Sablon.Properties.Settings.Default.HastaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HastaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HastaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HastaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HastaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dbo_tblPatolojikVeriler> dbo_tblPatolojikVerilers
		{
			get
			{
				return this.GetTable<dbo_tblPatolojikVeriler>();
			}
		}
		
		public System.Data.Linq.Table<tblTakipVerileri> tblTakipVerileris
		{
			get
			{
				return this.GetTable<tblTakipVerileri>();
			}
		}
		
		public System.Data.Linq.Table<tblDemografik_Ozellikleri> tblDemografik_Ozellikleris
		{
			get
			{
				return this.GetTable<tblDemografik_Ozellikleri>();
			}
		}
		
		public System.Data.Linq.Table<tblDoktor> tblDoktors
		{
			get
			{
				return this.GetTable<tblDoktor>();
			}
		}
		
		public System.Data.Linq.Table<tblHastaBilgileri> tblHastaBilgileris
		{
			get
			{
				return this.GetTable<tblHastaBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<tblOperatif_Ozellikler> tblOperatif_Ozelliklers
		{
			get
			{
				return this.GetTable<tblOperatif_Ozellikler>();
			}
		}
		
		public System.Data.Linq.Table<tblPosOperatif_Ozellikler> tblPosOperatif_Ozelliklers
		{
			get
			{
				return this.GetTable<tblPosOperatif_Ozellikler>();
			}
		}
		
		public System.Data.Linq.Table<tblOpTuru> tblOpTurus
		{
			get
			{
				return this.GetTable<tblOpTuru>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[dbo.tblPatolojikVeriler]")]
	public partial class dbo_tblPatolojikVeriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PATOLOJI;
		
		private string _ALT_GRUP;
		
		private System.Nullable<int> _FURHMAN_GRADE;
		
		private string _PATOLOJIK_EVRE;
		
		private string _CERRAHI_SINIR;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPATOLOJIChanging(string value);
    partial void OnPATOLOJIChanged();
    partial void OnALT_GRUPChanging(string value);
    partial void OnALT_GRUPChanged();
    partial void OnFURHMAN_GRADEChanging(System.Nullable<int> value);
    partial void OnFURHMAN_GRADEChanged();
    partial void OnPATOLOJIK_EVREChanging(string value);
    partial void OnPATOLOJIK_EVREChanged();
    partial void OnCERRAHI_SINIRChanging(string value);
    partial void OnCERRAHI_SINIRChanged();
    #endregion
		
		public dbo_tblPatolojikVeriler()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PATOLOJI", DbType="NVarChar(50)")]
		public string PATOLOJI
		{
			get
			{
				return this._PATOLOJI;
			}
			set
			{
				if ((this._PATOLOJI != value))
				{
					this.OnPATOLOJIChanging(value);
					this.SendPropertyChanging();
					this._PATOLOJI = value;
					this.SendPropertyChanged("PATOLOJI");
					this.OnPATOLOJIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALT_GRUP", DbType="NVarChar(150)")]
		public string ALT_GRUP
		{
			get
			{
				return this._ALT_GRUP;
			}
			set
			{
				if ((this._ALT_GRUP != value))
				{
					this.OnALT_GRUPChanging(value);
					this.SendPropertyChanging();
					this._ALT_GRUP = value;
					this.SendPropertyChanged("ALT_GRUP");
					this.OnALT_GRUPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FURHMAN_GRADE", DbType="Int")]
		public System.Nullable<int> FURHMAN_GRADE
		{
			get
			{
				return this._FURHMAN_GRADE;
			}
			set
			{
				if ((this._FURHMAN_GRADE != value))
				{
					this.OnFURHMAN_GRADEChanging(value);
					this.SendPropertyChanging();
					this._FURHMAN_GRADE = value;
					this.SendPropertyChanged("FURHMAN_GRADE");
					this.OnFURHMAN_GRADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PATOLOJIK_EVRE", DbType="NVarChar(20)")]
		public string PATOLOJIK_EVRE
		{
			get
			{
				return this._PATOLOJIK_EVRE;
			}
			set
			{
				if ((this._PATOLOJIK_EVRE != value))
				{
					this.OnPATOLOJIK_EVREChanging(value);
					this.SendPropertyChanging();
					this._PATOLOJIK_EVRE = value;
					this.SendPropertyChanged("PATOLOJIK_EVRE");
					this.OnPATOLOJIK_EVREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CERRAHI_SINIR", DbType="NVarChar(50)")]
		public string CERRAHI_SINIR
		{
			get
			{
				return this._CERRAHI_SINIR;
			}
			set
			{
				if ((this._CERRAHI_SINIR != value))
				{
					this.OnCERRAHI_SINIRChanging(value);
					this.SendPropertyChanging();
					this._CERRAHI_SINIR = value;
					this.SendPropertyChanged("CERRAHI_SINIR");
					this.OnCERRAHI_SINIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_dbo_tblPatolojikVeriler", Storage="_tblHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.dbo_tblPatolojikVerilers.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.dbo_tblPatolojikVerilers.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTakipVerileri")]
	public partial class tblTakipVerileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _POSTOP_3_AY_LOKAL_NUKS;
		
		private System.Nullable<decimal> _POSTOP_3_AY_KREATIN;
		
		private string _POSTOP_6_AY_LOKAL_NUKS;
		
		private System.Nullable<decimal> _POSTOP_6_AY_KREATIN;
		
		private string _POSTOP_12_AY_LOKAL_NUKS;
		
		private System.Nullable<decimal> _POSTOP_12_AY_KREATIN;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPOSTOP_3_AY_LOKAL_NUKSChanging(string value);
    partial void OnPOSTOP_3_AY_LOKAL_NUKSChanged();
    partial void OnPOSTOP_3_AY_KREATINChanging(System.Nullable<decimal> value);
    partial void OnPOSTOP_3_AY_KREATINChanged();
    partial void OnPOSTOP_6_AY_LOKAL_NUKSChanging(string value);
    partial void OnPOSTOP_6_AY_LOKAL_NUKSChanged();
    partial void OnPOSTOP_6_AY_KREATINChanging(System.Nullable<decimal> value);
    partial void OnPOSTOP_6_AY_KREATINChanged();
    partial void OnPOSTOP_12_AY_LOKAL_NUKSChanging(string value);
    partial void OnPOSTOP_12_AY_LOKAL_NUKSChanged();
    partial void OnPOSTOP_12_AY_KREATINChanging(System.Nullable<decimal> value);
    partial void OnPOSTOP_12_AY_KREATINChanged();
    #endregion
		
		public tblTakipVerileri()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_3_AY_LOKAL_NUKS", DbType="NVarChar(255)")]
		public string POSTOP_3_AY_LOKAL_NUKS
		{
			get
			{
				return this._POSTOP_3_AY_LOKAL_NUKS;
			}
			set
			{
				if ((this._POSTOP_3_AY_LOKAL_NUKS != value))
				{
					this.OnPOSTOP_3_AY_LOKAL_NUKSChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_3_AY_LOKAL_NUKS = value;
					this.SendPropertyChanged("POSTOP_3_AY_LOKAL_NUKS");
					this.OnPOSTOP_3_AY_LOKAL_NUKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_3_AY_KREATIN", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> POSTOP_3_AY_KREATIN
		{
			get
			{
				return this._POSTOP_3_AY_KREATIN;
			}
			set
			{
				if ((this._POSTOP_3_AY_KREATIN != value))
				{
					this.OnPOSTOP_3_AY_KREATINChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_3_AY_KREATIN = value;
					this.SendPropertyChanged("POSTOP_3_AY_KREATIN");
					this.OnPOSTOP_3_AY_KREATINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_6_AY_LOKAL_NUKS", DbType="NVarChar(255)")]
		public string POSTOP_6_AY_LOKAL_NUKS
		{
			get
			{
				return this._POSTOP_6_AY_LOKAL_NUKS;
			}
			set
			{
				if ((this._POSTOP_6_AY_LOKAL_NUKS != value))
				{
					this.OnPOSTOP_6_AY_LOKAL_NUKSChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_6_AY_LOKAL_NUKS = value;
					this.SendPropertyChanged("POSTOP_6_AY_LOKAL_NUKS");
					this.OnPOSTOP_6_AY_LOKAL_NUKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_6_AY_KREATIN", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> POSTOP_6_AY_KREATIN
		{
			get
			{
				return this._POSTOP_6_AY_KREATIN;
			}
			set
			{
				if ((this._POSTOP_6_AY_KREATIN != value))
				{
					this.OnPOSTOP_6_AY_KREATINChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_6_AY_KREATIN = value;
					this.SendPropertyChanged("POSTOP_6_AY_KREATIN");
					this.OnPOSTOP_6_AY_KREATINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_12_AY_LOKAL_NUKS", DbType="NVarChar(255)")]
		public string POSTOP_12_AY_LOKAL_NUKS
		{
			get
			{
				return this._POSTOP_12_AY_LOKAL_NUKS;
			}
			set
			{
				if ((this._POSTOP_12_AY_LOKAL_NUKS != value))
				{
					this.OnPOSTOP_12_AY_LOKAL_NUKSChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_12_AY_LOKAL_NUKS = value;
					this.SendPropertyChanged("POSTOP_12_AY_LOKAL_NUKS");
					this.OnPOSTOP_12_AY_LOKAL_NUKSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_12_AY_KREATIN", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> POSTOP_12_AY_KREATIN
		{
			get
			{
				return this._POSTOP_12_AY_KREATIN;
			}
			set
			{
				if ((this._POSTOP_12_AY_KREATIN != value))
				{
					this.OnPOSTOP_12_AY_KREATINChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_12_AY_KREATIN = value;
					this.SendPropertyChanged("POSTOP_12_AY_KREATIN");
					this.OnPOSTOP_12_AY_KREATINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblTakipVerileri", Storage="_tblHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblTakipVerileris.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblTakipVerileris.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDemografik_Ozellikleri")]
	public partial class tblDemografik_Ozellikleri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private System.Nullable<int> _Yas;
		
		private System.Nullable<int> _Boy;
		
		private System.Nullable<int> _Kilo;
		
		private System.Nullable<int> _BMI;
		
		private System.Nullable<int> _ASA;
		
		private string _Dr;
		
		private string _Cins;
		
		private string _Taraf;
		
		private string _Lokalizasyon;
		
		private System.Nullable<int> _Boyut;
		
		private string _KO_Morbidite;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnYasChanging(System.Nullable<int> value);
    partial void OnYasChanged();
    partial void OnBoyChanging(System.Nullable<int> value);
    partial void OnBoyChanged();
    partial void OnKiloChanging(System.Nullable<int> value);
    partial void OnKiloChanged();
    partial void OnBMIChanging(System.Nullable<int> value);
    partial void OnBMIChanged();
    partial void OnASAChanging(System.Nullable<int> value);
    partial void OnASAChanged();
    partial void OnDrChanging(string value);
    partial void OnDrChanged();
    partial void OnCinsChanging(string value);
    partial void OnCinsChanged();
    partial void OnTarafChanging(string value);
    partial void OnTarafChanged();
    partial void OnLokalizasyonChanging(string value);
    partial void OnLokalizasyonChanged();
    partial void OnBoyutChanging(System.Nullable<int> value);
    partial void OnBoyutChanged();
    partial void OnKO_MorbiditeChanging(string value);
    partial void OnKO_MorbiditeChanged();
    #endregion
		
		public tblDemografik_Ozellikleri()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yas", DbType="Int")]
		public System.Nullable<int> Yas
		{
			get
			{
				return this._Yas;
			}
			set
			{
				if ((this._Yas != value))
				{
					this.OnYasChanging(value);
					this.SendPropertyChanging();
					this._Yas = value;
					this.SendPropertyChanged("Yas");
					this.OnYasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boy", DbType="Int")]
		public System.Nullable<int> Boy
		{
			get
			{
				return this._Boy;
			}
			set
			{
				if ((this._Boy != value))
				{
					this.OnBoyChanging(value);
					this.SendPropertyChanging();
					this._Boy = value;
					this.SendPropertyChanged("Boy");
					this.OnBoyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilo", DbType="Int")]
		public System.Nullable<int> Kilo
		{
			get
			{
				return this._Kilo;
			}
			set
			{
				if ((this._Kilo != value))
				{
					this.OnKiloChanging(value);
					this.SendPropertyChanging();
					this._Kilo = value;
					this.SendPropertyChanged("Kilo");
					this.OnKiloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BMI", DbType="Int")]
		public System.Nullable<int> BMI
		{
			get
			{
				return this._BMI;
			}
			set
			{
				if ((this._BMI != value))
				{
					this.OnBMIChanging(value);
					this.SendPropertyChanging();
					this._BMI = value;
					this.SendPropertyChanged("BMI");
					this.OnBMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASA", DbType="Int")]
		public System.Nullable<int> ASA
		{
			get
			{
				return this._ASA;
			}
			set
			{
				if ((this._ASA != value))
				{
					this.OnASAChanging(value);
					this.SendPropertyChanging();
					this._ASA = value;
					this.SendPropertyChanged("ASA");
					this.OnASAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dr", DbType="NVarChar(100)")]
		public string Dr
		{
			get
			{
				return this._Dr;
			}
			set
			{
				if ((this._Dr != value))
				{
					this.OnDrChanging(value);
					this.SendPropertyChanging();
					this._Dr = value;
					this.SendPropertyChanged("Dr");
					this.OnDrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cins", DbType="NVarChar(100)")]
		public string Cins
		{
			get
			{
				return this._Cins;
			}
			set
			{
				if ((this._Cins != value))
				{
					this.OnCinsChanging(value);
					this.SendPropertyChanging();
					this._Cins = value;
					this.SendPropertyChanged("Cins");
					this.OnCinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taraf", DbType="NVarChar(5)")]
		public string Taraf
		{
			get
			{
				return this._Taraf;
			}
			set
			{
				if ((this._Taraf != value))
				{
					this.OnTarafChanging(value);
					this.SendPropertyChanging();
					this._Taraf = value;
					this.SendPropertyChanged("Taraf");
					this.OnTarafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokalizasyon", DbType="NVarChar(200)")]
		public string Lokalizasyon
		{
			get
			{
				return this._Lokalizasyon;
			}
			set
			{
				if ((this._Lokalizasyon != value))
				{
					this.OnLokalizasyonChanging(value);
					this.SendPropertyChanging();
					this._Lokalizasyon = value;
					this.SendPropertyChanged("Lokalizasyon");
					this.OnLokalizasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="Int")]
		public System.Nullable<int> Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this.OnBoyutChanging(value);
					this.SendPropertyChanging();
					this._Boyut = value;
					this.SendPropertyChanged("Boyut");
					this.OnBoyutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KO_Morbidite", DbType="NVarChar(200)")]
		public string KO_Morbidite
		{
			get
			{
				return this._KO_Morbidite;
			}
			set
			{
				if ((this._KO_Morbidite != value))
				{
					this.OnKO_MorbiditeChanging(value);
					this.SendPropertyChanging();
					this._KO_Morbidite = value;
					this.SendPropertyChanged("KO_Morbidite");
					this.OnKO_MorbiditeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblDemografik_Ozellikleri", Storage="_tblHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblDemografik_Ozellikleris.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblDemografik_Ozellikleris.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDoktor")]
	public partial class tblDoktor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DrAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDrAdiChanging(string value);
    partial void OnDrAdiChanged();
    #endregion
		
		public tblDoktor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrAdi", DbType="NVarChar(100)")]
		public string DrAdi
		{
			get
			{
				return this._DrAdi;
			}
			set
			{
				if ((this._DrAdi != value))
				{
					this.OnDrAdiChanging(value);
					this.SendPropertyChanging();
					this._DrAdi = value;
					this.SendPropertyChanged("DrAdi");
					this.OnDrAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHastaBilgileri")]
	public partial class tblHastaBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Protokol;
		
		private System.Nullable<System.DateTime> _OPTarihi;
		
		private string _OPTuru;
		
		private System.Nullable<int> _Takip;
		
		private System.Nullable<int> _ANAH;
		
		private EntitySet<dbo_tblPatolojikVeriler> _dbo_tblPatolojikVerilers;
		
		private EntitySet<tblTakipVerileri> _tblTakipVerileris;
		
		private EntitySet<tblDemografik_Ozellikleri> _tblDemografik_Ozellikleris;
		
		private EntitySet<tblOperatif_Ozellikler> _tblOperatif_Ozelliklers;
		
		private EntitySet<tblPosOperatif_Ozellikler> _tblPosOperatif_Ozelliklers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnProtokolChanging(string value);
    partial void OnProtokolChanged();
    partial void OnOPTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOPTarihiChanged();
    partial void OnOPTuruChanging(string value);
    partial void OnOPTuruChanged();
    partial void OnTakipChanging(System.Nullable<int> value);
    partial void OnTakipChanged();
    partial void OnANAHChanging(System.Nullable<int> value);
    partial void OnANAHChanged();
    #endregion
		
		public tblHastaBilgileri()
		{
			this._dbo_tblPatolojikVerilers = new EntitySet<dbo_tblPatolojikVeriler>(new Action<dbo_tblPatolojikVeriler>(this.attach_dbo_tblPatolojikVerilers), new Action<dbo_tblPatolojikVeriler>(this.detach_dbo_tblPatolojikVerilers));
			this._tblTakipVerileris = new EntitySet<tblTakipVerileri>(new Action<tblTakipVerileri>(this.attach_tblTakipVerileris), new Action<tblTakipVerileri>(this.detach_tblTakipVerileris));
			this._tblDemografik_Ozellikleris = new EntitySet<tblDemografik_Ozellikleri>(new Action<tblDemografik_Ozellikleri>(this.attach_tblDemografik_Ozellikleris), new Action<tblDemografik_Ozellikleri>(this.detach_tblDemografik_Ozellikleris));
			this._tblOperatif_Ozelliklers = new EntitySet<tblOperatif_Ozellikler>(new Action<tblOperatif_Ozellikler>(this.attach_tblOperatif_Ozelliklers), new Action<tblOperatif_Ozellikler>(this.detach_tblOperatif_Ozelliklers));
			this._tblPosOperatif_Ozelliklers = new EntitySet<tblPosOperatif_Ozellikler>(new Action<tblPosOperatif_Ozellikler>(this.attach_tblPosOperatif_Ozelliklers), new Action<tblPosOperatif_Ozellikler>(this.detach_tblPosOperatif_Ozelliklers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protokol", DbType="NVarChar(100)")]
		public string Protokol
		{
			get
			{
				return this._Protokol;
			}
			set
			{
				if ((this._Protokol != value))
				{
					this.OnProtokolChanging(value);
					this.SendPropertyChanging();
					this._Protokol = value;
					this.SendPropertyChanged("Protokol");
					this.OnProtokolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> OPTarihi
		{
			get
			{
				return this._OPTarihi;
			}
			set
			{
				if ((this._OPTarihi != value))
				{
					this.OnOPTarihiChanging(value);
					this.SendPropertyChanging();
					this._OPTarihi = value;
					this.SendPropertyChanged("OPTarihi");
					this.OnOPTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPTuru", DbType="NVarChar(150)")]
		public string OPTuru
		{
			get
			{
				return this._OPTuru;
			}
			set
			{
				if ((this._OPTuru != value))
				{
					this.OnOPTuruChanging(value);
					this.SendPropertyChanging();
					this._OPTuru = value;
					this.SendPropertyChanged("OPTuru");
					this.OnOPTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="Int")]
		public System.Nullable<int> Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANAH", DbType="Int")]
		public System.Nullable<int> ANAH
		{
			get
			{
				return this._ANAH;
			}
			set
			{
				if ((this._ANAH != value))
				{
					this.OnANAHChanging(value);
					this.SendPropertyChanging();
					this._ANAH = value;
					this.SendPropertyChanged("ANAH");
					this.OnANAHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_dbo_tblPatolojikVeriler", Storage="_dbo_tblPatolojikVerilers", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<dbo_tblPatolojikVeriler> dbo_tblPatolojikVerilers
		{
			get
			{
				return this._dbo_tblPatolojikVerilers;
			}
			set
			{
				this._dbo_tblPatolojikVerilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblTakipVerileri", Storage="_tblTakipVerileris", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblTakipVerileri> tblTakipVerileris
		{
			get
			{
				return this._tblTakipVerileris;
			}
			set
			{
				this._tblTakipVerileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblDemografik_Ozellikleri", Storage="_tblDemografik_Ozellikleris", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblDemografik_Ozellikleri> tblDemografik_Ozellikleris
		{
			get
			{
				return this._tblDemografik_Ozellikleris;
			}
			set
			{
				this._tblDemografik_Ozellikleris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblOperatif_Ozellikler", Storage="_tblOperatif_Ozelliklers", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblOperatif_Ozellikler> tblOperatif_Ozelliklers
		{
			get
			{
				return this._tblOperatif_Ozelliklers;
			}
			set
			{
				this._tblOperatif_Ozelliklers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPosOperatif_Ozellikler", Storage="_tblPosOperatif_Ozelliklers", ThisKey="ID", OtherKey="HastaID")]
		public EntitySet<tblPosOperatif_Ozellikler> tblPosOperatif_Ozelliklers
		{
			get
			{
				return this._tblPosOperatif_Ozelliklers;
			}
			set
			{
				this._tblPosOperatif_Ozelliklers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dbo_tblPatolojikVerilers(dbo_tblPatolojikVeriler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_dbo_tblPatolojikVerilers(dbo_tblPatolojikVeriler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblTakipVerileris(tblTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblTakipVerileris(tblTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblDemografik_Ozellikleris(tblDemografik_Ozellikleri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblDemografik_Ozellikleris(tblDemografik_Ozellikleri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblOperatif_Ozelliklers(tblOperatif_Ozellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblOperatif_Ozelliklers(tblOperatif_Ozellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblPosOperatif_Ozelliklers(tblPosOperatif_Ozellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblPosOperatif_Ozelliklers(tblPosOperatif_Ozellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOperatif_Ozellikler")]
	public partial class tblOperatif_Ozellikler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PKS_Aciklama;
		
		private string _SIK;
		
		private string _CO_Operasyon;
		
		private System.Nullable<int> _iskemi;
		
		private System.Nullable<int> _Port_Sayisi;
		
		private string _Yardim_YNT;
		
		private System.Nullable<int> _Sure;
		
		private string _DREN;
		
		private System.Nullable<int> _KANAMA;
		
		private System.Nullable<int> _PIYES;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPKS_AciklamaChanging(string value);
    partial void OnPKS_AciklamaChanged();
    partial void OnSIKChanging(string value);
    partial void OnSIKChanged();
    partial void OnCO_OperasyonChanging(string value);
    partial void OnCO_OperasyonChanged();
    partial void OniskemiChanging(System.Nullable<int> value);
    partial void OniskemiChanged();
    partial void OnPort_SayisiChanging(System.Nullable<int> value);
    partial void OnPort_SayisiChanged();
    partial void OnYardim_YNTChanging(string value);
    partial void OnYardim_YNTChanged();
    partial void OnSureChanging(System.Nullable<int> value);
    partial void OnSureChanged();
    partial void OnDRENChanging(string value);
    partial void OnDRENChanged();
    partial void OnKANAMAChanging(System.Nullable<int> value);
    partial void OnKANAMAChanged();
    partial void OnPIYESChanging(System.Nullable<int> value);
    partial void OnPIYESChanged();
    #endregion
		
		public tblOperatif_Ozellikler()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PKS_Aciklama", DbType="NVarChar(20)")]
		public string PKS_Aciklama
		{
			get
			{
				return this._PKS_Aciklama;
			}
			set
			{
				if ((this._PKS_Aciklama != value))
				{
					this.OnPKS_AciklamaChanging(value);
					this.SendPropertyChanging();
					this._PKS_Aciklama = value;
					this.SendPropertyChanged("PKS_Aciklama");
					this.OnPKS_AciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIK", DbType="NVarChar(50)")]
		public string SIK
		{
			get
			{
				return this._SIK;
			}
			set
			{
				if ((this._SIK != value))
				{
					this.OnSIKChanging(value);
					this.SendPropertyChanging();
					this._SIK = value;
					this.SendPropertyChanged("SIK");
					this.OnSIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_Operasyon", DbType="NVarChar(100)")]
		public string CO_Operasyon
		{
			get
			{
				return this._CO_Operasyon;
			}
			set
			{
				if ((this._CO_Operasyon != value))
				{
					this.OnCO_OperasyonChanging(value);
					this.SendPropertyChanging();
					this._CO_Operasyon = value;
					this.SendPropertyChanged("CO_Operasyon");
					this.OnCO_OperasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iskemi", DbType="Int")]
		public System.Nullable<int> iskemi
		{
			get
			{
				return this._iskemi;
			}
			set
			{
				if ((this._iskemi != value))
				{
					this.OniskemiChanging(value);
					this.SendPropertyChanging();
					this._iskemi = value;
					this.SendPropertyChanged("iskemi");
					this.OniskemiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port_Sayisi", DbType="Int")]
		public System.Nullable<int> Port_Sayisi
		{
			get
			{
				return this._Port_Sayisi;
			}
			set
			{
				if ((this._Port_Sayisi != value))
				{
					this.OnPort_SayisiChanging(value);
					this.SendPropertyChanging();
					this._Port_Sayisi = value;
					this.SendPropertyChanged("Port_Sayisi");
					this.OnPort_SayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yardim_YNT", DbType="NVarChar(50)")]
		public string Yardim_YNT
		{
			get
			{
				return this._Yardim_YNT;
			}
			set
			{
				if ((this._Yardim_YNT != value))
				{
					this.OnYardim_YNTChanging(value);
					this.SendPropertyChanging();
					this._Yardim_YNT = value;
					this.SendPropertyChanged("Yardim_YNT");
					this.OnYardim_YNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int")]
		public System.Nullable<int> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DREN", DbType="NVarChar(100)")]
		public string DREN
		{
			get
			{
				return this._DREN;
			}
			set
			{
				if ((this._DREN != value))
				{
					this.OnDRENChanging(value);
					this.SendPropertyChanging();
					this._DREN = value;
					this.SendPropertyChanged("DREN");
					this.OnDRENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KANAMA", DbType="Int")]
		public System.Nullable<int> KANAMA
		{
			get
			{
				return this._KANAMA;
			}
			set
			{
				if ((this._KANAMA != value))
				{
					this.OnKANAMAChanging(value);
					this.SendPropertyChanging();
					this._KANAMA = value;
					this.SendPropertyChanged("KANAMA");
					this.OnKANAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIYES", DbType="Int")]
		public System.Nullable<int> PIYES
		{
			get
			{
				return this._PIYES;
			}
			set
			{
				if ((this._PIYES != value))
				{
					this.OnPIYESChanging(value);
					this.SendPropertyChanging();
					this._PIYES = value;
					this.SendPropertyChanged("PIYES");
					this.OnPIYESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblOperatif_Ozellikler", Storage="_tblHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblOperatif_Ozelliklers.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblOperatif_Ozelliklers.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPosOperatif_Ozellikler")]
	public partial class tblPosOperatif_Ozellikler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _HastaID;
		
		private string _PEROP_VE_ERKEN_KOMP;
		
		private System.Nullable<decimal> _POSTOP_ANALIZ;
		
		private string _SONDA;
		
		private System.Nullable<int> _HOSP_SURESI;
		
		private System.Nullable<decimal> _PREOP_KREATIN;
		
		private System.Nullable<decimal> _POSTOP_KREATIN;
		
		private System.Nullable<decimal> _PREOP_HCT;
		
		private System.Nullable<decimal> _POSTOP_HCT;
		
		private System.Nullable<decimal> _PREOP_HB;
		
		private System.Nullable<decimal> _POSTOP_HB;
		
		private string _TAKIP;
		
		private string _TEL;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHastaIDChanging(System.Nullable<int> value);
    partial void OnHastaIDChanged();
    partial void OnPEROP_VE_ERKEN_KOMPChanging(string value);
    partial void OnPEROP_VE_ERKEN_KOMPChanged();
    partial void OnPOSTOP_ANALIZChanging(System.Nullable<decimal> value);
    partial void OnPOSTOP_ANALIZChanged();
    partial void OnSONDAChanging(string value);
    partial void OnSONDAChanged();
    partial void OnHOSP_SURESIChanging(System.Nullable<int> value);
    partial void OnHOSP_SURESIChanged();
    partial void OnPREOP_KREATINChanging(System.Nullable<decimal> value);
    partial void OnPREOP_KREATINChanged();
    partial void OnPOSTOP_KREATINChanging(System.Nullable<decimal> value);
    partial void OnPOSTOP_KREATINChanged();
    partial void OnPREOP_HCTChanging(System.Nullable<decimal> value);
    partial void OnPREOP_HCTChanged();
    partial void OnPOSTOP_HCTChanging(System.Nullable<decimal> value);
    partial void OnPOSTOP_HCTChanged();
    partial void OnPREOP_HBChanging(System.Nullable<decimal> value);
    partial void OnPREOP_HBChanged();
    partial void OnPOSTOP_HBChanging(System.Nullable<decimal> value);
    partial void OnPOSTOP_HBChanged();
    partial void OnTAKIPChanging(string value);
    partial void OnTAKIPChanged();
    partial void OnTELChanging(string value);
    partial void OnTELChanged();
    #endregion
		
		public tblPosOperatif_Ozellikler()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaID", DbType="Int")]
		public System.Nullable<int> HastaID
		{
			get
			{
				return this._HastaID;
			}
			set
			{
				if ((this._HastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHastaIDChanging(value);
					this.SendPropertyChanging();
					this._HastaID = value;
					this.SendPropertyChanged("HastaID");
					this.OnHastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PEROP_VE_ERKEN_KOMP", DbType="NVarChar(100)")]
		public string PEROP_VE_ERKEN_KOMP
		{
			get
			{
				return this._PEROP_VE_ERKEN_KOMP;
			}
			set
			{
				if ((this._PEROP_VE_ERKEN_KOMP != value))
				{
					this.OnPEROP_VE_ERKEN_KOMPChanging(value);
					this.SendPropertyChanging();
					this._PEROP_VE_ERKEN_KOMP = value;
					this.SendPropertyChanged("PEROP_VE_ERKEN_KOMP");
					this.OnPEROP_VE_ERKEN_KOMPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_ANALIZ", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> POSTOP_ANALIZ
		{
			get
			{
				return this._POSTOP_ANALIZ;
			}
			set
			{
				if ((this._POSTOP_ANALIZ != value))
				{
					this.OnPOSTOP_ANALIZChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_ANALIZ = value;
					this.SendPropertyChanged("POSTOP_ANALIZ");
					this.OnPOSTOP_ANALIZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONDA", DbType="NVarChar(255)")]
		public string SONDA
		{
			get
			{
				return this._SONDA;
			}
			set
			{
				if ((this._SONDA != value))
				{
					this.OnSONDAChanging(value);
					this.SendPropertyChanging();
					this._SONDA = value;
					this.SendPropertyChanged("SONDA");
					this.OnSONDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOSP_SURESI", DbType="Int")]
		public System.Nullable<int> HOSP_SURESI
		{
			get
			{
				return this._HOSP_SURESI;
			}
			set
			{
				if ((this._HOSP_SURESI != value))
				{
					this.OnHOSP_SURESIChanging(value);
					this.SendPropertyChanging();
					this._HOSP_SURESI = value;
					this.SendPropertyChanged("HOSP_SURESI");
					this.OnHOSP_SURESIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREOP_KREATIN", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PREOP_KREATIN
		{
			get
			{
				return this._PREOP_KREATIN;
			}
			set
			{
				if ((this._PREOP_KREATIN != value))
				{
					this.OnPREOP_KREATINChanging(value);
					this.SendPropertyChanging();
					this._PREOP_KREATIN = value;
					this.SendPropertyChanged("PREOP_KREATIN");
					this.OnPREOP_KREATINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_KREATIN", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> POSTOP_KREATIN
		{
			get
			{
				return this._POSTOP_KREATIN;
			}
			set
			{
				if ((this._POSTOP_KREATIN != value))
				{
					this.OnPOSTOP_KREATINChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_KREATIN = value;
					this.SendPropertyChanged("POSTOP_KREATIN");
					this.OnPOSTOP_KREATINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREOP_HCT", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PREOP_HCT
		{
			get
			{
				return this._PREOP_HCT;
			}
			set
			{
				if ((this._PREOP_HCT != value))
				{
					this.OnPREOP_HCTChanging(value);
					this.SendPropertyChanging();
					this._PREOP_HCT = value;
					this.SendPropertyChanged("PREOP_HCT");
					this.OnPREOP_HCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_HCT", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> POSTOP_HCT
		{
			get
			{
				return this._POSTOP_HCT;
			}
			set
			{
				if ((this._POSTOP_HCT != value))
				{
					this.OnPOSTOP_HCTChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_HCT = value;
					this.SendPropertyChanged("POSTOP_HCT");
					this.OnPOSTOP_HCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREOP_HB", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> PREOP_HB
		{
			get
			{
				return this._PREOP_HB;
			}
			set
			{
				if ((this._PREOP_HB != value))
				{
					this.OnPREOP_HBChanging(value);
					this.SendPropertyChanging();
					this._PREOP_HB = value;
					this.SendPropertyChanged("PREOP_HB");
					this.OnPREOP_HBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTOP_HB", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> POSTOP_HB
		{
			get
			{
				return this._POSTOP_HB;
			}
			set
			{
				if ((this._POSTOP_HB != value))
				{
					this.OnPOSTOP_HBChanging(value);
					this.SendPropertyChanging();
					this._POSTOP_HB = value;
					this.SendPropertyChanged("POSTOP_HB");
					this.OnPOSTOP_HBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAKIP", DbType="NVarChar(300)")]
		public string TAKIP
		{
			get
			{
				return this._TAKIP;
			}
			set
			{
				if ((this._TAKIP != value))
				{
					this.OnTAKIPChanging(value);
					this.SendPropertyChanging();
					this._TAKIP = value;
					this.SendPropertyChanged("TAKIP");
					this.OnTAKIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL", DbType="NVarChar(100)")]
		public string TEL
		{
			get
			{
				return this._TEL;
			}
			set
			{
				if ((this._TEL != value))
				{
					this.OnTELChanging(value);
					this.SendPropertyChanging();
					this._TEL = value;
					this.SendPropertyChanged("TEL");
					this.OnTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPosOperatif_Ozellikler", Storage="_tblHastaBilgileri", ThisKey="HastaID", OtherKey="ID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblPosOperatif_Ozelliklers.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblPosOperatif_Ozelliklers.Add(this);
						this._HastaID = value.ID;
					}
					else
					{
						this._HastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOpTuru")]
	public partial class tblOpTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _OpTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    #endregion
		
		public tblOpTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(350)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
